[package]
name = "geoparquet-batch-writer-derive"
version = "0.1.0"
license = "MIT"
edition = "2024"
publish = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
