[package]
name = "parquet-batch-writer-derive"
description = "Derive macros for convenient batch writing of Parquet files with optional GeoParquet support"
homepage = "https://github.com/KotobaMedia/parquet-batch-writer/"
repository = "https://github.com/KotobaMedia/parquet-batch-writer/"
version = "0.1.4"
license = "MIT"
edition = "2024"
publish = true

[lib]
proc-macro = true

[dependencies]
darling = "0.21"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
