[package]
name = "geoparquet-batch-writer"
description = "A library for convenient batch writing of Parquet files with optional GeoParquet support"
homepage = "https://github.com/KotobaMedia/geoparquet-batch-writer/"
repository = "https://github.com/KotobaMedia/geoparquet-batch-writer/"
version = "0.1.4"
license = "MIT"
edition = "2024"
keywords = ["parquet", "geoparquet", "arrow"]
publish = true

[features]
default = ["geo"]
geo = [
    "dep:geo-types",
    "dep:geoarrow-array",
    "dep:geoarrow-schema",
    "dep:geoparquet",
]

[dependencies]
thiserror = "2"
arrow-array = "56"
arrow-schema = "56"
arrow-buffer = "56"
geo-types = { version = "0.7", optional = true }
geoarrow-array = { version = "0.5", optional = true }
geoarrow-schema = { version = "0.5", optional = true }
geoparquet = { version = "0.5", optional = true }
parquet = { version = "56", features = ["arrow"] }
geoparquet-batch-writer-derive = { version = "=0.1.4", path = "../derive" }

[dev-dependencies]
tempfile = "3"
anyhow = "1"
duckdb = { version = "1.4", features = ["bundled"] }
