name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Test workspace
        run: |
          cargo test --workspace --all-targets --locked
